# Generated by Django 5.1.6 on 2025-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups_and_Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_ID', models.CharField(max_length=10)),
                ('Region', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Affected_Areas', models.TextField()),
            ],
        ),
    ]
